apiVersion: v1
kind: Secret
metadata:
  name: argocd-apps-manifests
  namespace: argo-cd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: "https://github.com/devqx/commit-argocd.git"
  type: "git"
