apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-app-set
  namespace: argo-cd
spec:
  generators:
  - git:
      repoURL: "https://github.com/devqx/commit-argocd.git"
      revision: main
      files:
        - path: "apps/prod/"
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: '{project}}'
      source:
        chart: commit-apps-chart
        repoURL: "https://raw.githubusercontent.com/devqx/commit-helm-charts/gh-pages"
        targetRevision: 0.1.0
        helm:
          values: |-
            {{values}}
      destination:
        name: 'in-cluster'
        namespace: '{{namespace}}'
      syncPolicy:
        automated: # automated sync by default, retries failed attempts 5 times with following delays between attempts (5s,10s,20s,40s,80s); retry controlled using 'retry' field.
          prune: true # Specifies if resource should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target kubernetes cluster and no git changes detected ( false by default ).
          allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
        syncOptions: # Sync Options which helps to modify sync behavior.
          - Validate=false # disables resource validation ( same as 'kubectl apply --validate= false' ) ( true by default ).
          - CreateNamespace=true # Namespace auto creation ensures that namespace specified as the application destination exists in the destination cluster
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 5 # number of failed sync attempts retries; unlimited number of attempts of less than 0
          backoff:
            duration: 5s # the amount of time to back off, can be "2m", "1h"
            factor: 2 # a factor to multiply the base duration after each failed retry
            maxDuration: 3m # the maximum amount of time allowed for the backoff strategy

        ignoreDifferences:
          - group: apps
            kind: Deployment
            jsonPointers:
              - /spec/replicas
          - group: "*"
            kind: "*"
            managedFieldsManagers:
              - kube-controller-manager
