apiVersion: v1
kind: Secret
metadata:
  name: git-repo-credentials
  namespace: argo-cd
  labels:
    argocd.argoproj.io/secret-type: repo-creds

stringData:
  url: https://github.com/devqx
  type: git
  username: ${git_username}
  password: ${git_password}